name: GitHub Profile Metrics

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: mrityu12                         # <<< change if needed
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
